# swarm-policy.sh — this repo's per-repo POLICY layer (ADR 0002, #12).
# Plain KEY=value beside swarm-identity.sh; see .sandcastle/policy-lib.sh
# for the knobs, the fixed trigger vocabulary, and the defaults.
# Generated by `factory onboard policy` (#12).
LANDING=pr
MERGE_AUTHORITY=human
