/**
 * Platform detection utilities for Electron, Capacitor (Android), Cordova, and
 * browser environments.
 */

import { isCapacitor, getBackendInfo } from './capacitor';

interface ElectronAPI {
  isElectron: true;
  platform: string;
  getBackendPort: () => Promise<number>;
  getDataDir: () => Promise<string>;
  getApiToken: () => Promise<string>;
}

let cachedBackendUrl: string | null = null;
let cachedApiToken: string | null = null;

/**
 * Fixed fallback token used in dev/test (browser) mode. Mirrors the backend's
 * DevAPIToken so `npm run dev` and the Playwright e2e suite work with zero
 * setup. Bundled/production Electron uses a random per-launch token exposed
 * via IPC instead.
 */
const DEV_API_TOKEN = 'matou-dev';

/**
 * Check if running inside Electron.
 */
export function isElectron(): boolean {
  return !!(window as unknown as { electronAPI?: ElectronAPI }).electronAPI?.isElectron;
}

/**
 * Check if running inside Cordova.
 *
 * Capacitor is a separate check — it sets `window.Capacitor`, not
 * `window.cordova` — see isCapacitor() in ./capacitor.
 */
export function isCordova(): boolean {
  return !!(window as unknown as { cordova?: unknown }).cordova;
}

export { isCapacitor };

/**
 * Check if running in a regular browser (dev or web deployment).
 */
export function isBrowser(): boolean {
  return !isElectron() && !isCordova() && !isCapacitor();
}

/**
 * Get the backend URL based on the current platform.
 * - Electron: dynamically allocated localhost port
 * - Capacitor: loopback port of the embedded Go backend, via the MatouBackend plugin
 * - Cordova: localhost with configured port
 * - Browser: from VITE_BACKEND_URL env var or default
 */
export async function getBackendUrl(): Promise<string> {
  if (cachedBackendUrl) return cachedBackendUrl;

  if (isElectron()) {
    const api = (window as unknown as { electronAPI: ElectronAPI }).electronAPI;
    const port = await api.getBackendPort();
    cachedBackendUrl = `http://127.0.0.1:${port}`;
    return cachedBackendUrl;
  }

  if (isCapacitor()) {
    const { port } = await getBackendInfo();
    cachedBackendUrl = `http://127.0.0.1:${port}`;
    return cachedBackendUrl;
  }

  // Browser and Cordova use the env var or default
  cachedBackendUrl = (import.meta.env.VITE_BACKEND_URL as string) || 'http://localhost:8080';
  return cachedBackendUrl;
}

/**
 * Get the backend URL synchronously (returns cached value or default).
 * Use getBackendUrl() for the async version that resolves Electron ports.
 *
 * On Capacitor there is no static default to fall back to — the port is only
 * known once the plugin has started the backend — so this returns an empty
 * string until getBackendUrl() has resolved. Boot awaits initBackendUrl()
 * before any request, so callers never see that window in practice.
 */
export function getBackendUrlSync(): string {
  if (cachedBackendUrl) return cachedBackendUrl;
  if (isCapacitor()) return '';
  return (import.meta.env.VITE_BACKEND_URL as string | undefined) ?? 'http://localhost:8080';
}

/**
 * Get the per-launch API token used to authenticate mutating backend requests.
 * - Electron: the random token generated by the main process, via IPC.
 * - Capacitor: the random token the MatouBackend plugin generated for this launch.
 * - Browser (dev/test): VITE_API_TOKEN env var, or the DEV_API_TOKEN constant.
 *
 * The dev token is never used on Capacitor: the embedded backend generates a
 * random token per launch, so falling back to 'matou-dev' would silently
 * produce 401s instead of a legible failure.
 */
export async function getApiToken(): Promise<string> {
  if (cachedApiToken) return cachedApiToken;

  if (isElectron()) {
    const api = (window as unknown as { electronAPI: ElectronAPI }).electronAPI;
    cachedApiToken = await api.getApiToken();
    return cachedApiToken;
  }

  if (isCapacitor()) {
    const { token } = await getBackendInfo();
    cachedApiToken = token;
    return cachedApiToken;
  }

  cachedApiToken = (import.meta.env.VITE_API_TOKEN as string | undefined) || DEV_API_TOKEN;
  return cachedApiToken;
}

/**
 * Get the API token synchronously (cached value, env var, or dev constant).
 * Use getApiToken() for the async version that resolves the Electron token.
 *
 * On Capacitor this returns an empty string until getApiToken() has resolved,
 * rather than the dev constant — see getApiToken().
 */
export function getApiTokenSync(): string {
  if (cachedApiToken) return cachedApiToken;
  if (isCapacitor()) return '';
  return (import.meta.env.VITE_API_TOKEN as string | undefined) ?? DEV_API_TOKEN;
}
