/**
 * Platform detection utilities for Electron, Cordova, and browser environments.
 */

interface ElectronAPI {
  isElectron: true;
  platform: string;
  getBackendPort: () => Promise<number>;
  getDataDir: () => Promise<string>;
  getApiToken: () => Promise<string>;
}

let cachedBackendUrl: string | null = null;
let cachedApiToken: string | null = null;

/**
 * Fixed fallback token used in dev/test (browser) mode. Mirrors the backend's
 * DevAPIToken so `npm run dev` and the Playwright e2e suite work with zero
 * setup. Bundled/production Electron uses a random per-launch token exposed
 * via IPC instead.
 */
const DEV_API_TOKEN = 'matou-dev';

/**
 * Check if running inside Electron.
 */
export function isElectron(): boolean {
  return !!(window as unknown as { electronAPI?: ElectronAPI }).electronAPI?.isElectron;
}

/**
 * Check if running inside Cordova/Capacitor.
 */
export function isCordova(): boolean {
  return !!(window as unknown as { cordova?: unknown }).cordova;
}

/**
 * Check if running in a regular browser (dev or web deployment).
 */
export function isBrowser(): boolean {
  return !isElectron() && !isCordova();
}

/**
 * Get the backend URL based on the current platform.
 * - Electron: dynamically allocated localhost port
 * - Cordova: localhost with configured port
 * - Browser: from VITE_BACKEND_URL env var or default
 */
export async function getBackendUrl(): Promise<string> {
  if (cachedBackendUrl) return cachedBackendUrl;

  if (isElectron()) {
    const api = (window as unknown as { electronAPI: ElectronAPI }).electronAPI;
    const port = await api.getBackendPort();
    cachedBackendUrl = `http://127.0.0.1:${port}`;
    return cachedBackendUrl;
  }

  // Browser and Cordova use the env var or default
  cachedBackendUrl = (import.meta.env.VITE_BACKEND_URL as string) || 'http://localhost:8080';
  return cachedBackendUrl;
}

/**
 * Get the backend URL synchronously (returns cached value or default).
 * Use getBackendUrl() for the async version that resolves Electron ports.
 */
export function getBackendUrlSync(): string {
  return cachedBackendUrl ?? (import.meta.env.VITE_BACKEND_URL as string | undefined) ?? 'http://localhost:8080';
}

/**
 * Get the per-launch API token used to authenticate mutating backend requests.
 * - Electron: the random token generated by the main process, via IPC.
 * - Browser (dev/test): VITE_API_TOKEN env var, or the DEV_API_TOKEN constant.
 */
export async function getApiToken(): Promise<string> {
  if (cachedApiToken) return cachedApiToken;

  if (isElectron()) {
    const api = (window as unknown as { electronAPI: ElectronAPI }).electronAPI;
    cachedApiToken = await api.getApiToken();
    return cachedApiToken;
  }

  cachedApiToken = (import.meta.env.VITE_API_TOKEN as string | undefined) || DEV_API_TOKEN;
  return cachedApiToken;
}

/**
 * Get the API token synchronously (cached value, env var, or dev constant).
 * Use getApiToken() for the async version that resolves the Electron token.
 */
export function getApiTokenSync(): string {
  return cachedApiToken ?? (import.meta.env.VITE_API_TOKEN as string | undefined) ?? DEV_API_TOKEN;
}
